---
services:

  ###########################################################
  # execute
  ###########################################################

  execute:
    image: nexus-hosted.docker02-teine.home.elysianskies.com/elise/lazarus:main
    entrypoint: python src
    privileged: true

    environment:
      - TZ=America/Denver

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: false

      - type: bind
        source: ${IAC_CONFIGURE_PROJECT_DIR}/lazarus
        target: /lazarus
        read_only: true

    devices:
      - /dev/usb/hiddev0
      - /dev/usb/hiddev1

    networks:
      - lazarus

###########################################################
# resources
###########################################################

networks:
  lazarus:
    name: lazarus
